name: CI

on:
  push:
  pull_request:

jobs:
  swift-build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift build
